#!/bin/bash

module load ucsc
module load igvtools

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_1min.bw data/Spikein_normalized_nucleosome_counts.S2_1min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_1min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_1min.tdf data/dm6.chrom.sizes

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_2min.bw data/Spikein_normalized_nucleosome_counts.S2_2min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_2min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_2min.tdf data/dm6.chrom.sizes

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_5min.bw data/Spikein_normalized_nucleosome_counts.S2_5min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_5min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_5min.tdf data/dm6.chrom.sizes

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_15min.bw data/Spikein_normalized_nucleosome_counts.S2_15min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_15min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_15min.tdf data/dm6.chrom.sizes

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_40min.bw data/Spikein_normalized_nucleosome_counts.S2_40min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_40min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_40min.tdf data/dm6.chrom.sizes

bigWigToBedGraph data/Spikein_normalized_nucleosome_counts.S2_60min.bw data/Spikein_normalized_nucleosome_counts.S2_60min.bedGraph
igvtools toTDF data/Spikein_normalized_nucleosome_counts.S2_60min.bedGraph data/Spikein_normalized_nucleosome_counts.S2_60min.tdf data/dm6.chrom.sizes

rm data/*.bedGraph